# $ docker-compose -f mariadbAdmin.yaml up
# http://localhost:8080
# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: pwd

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
      
