# SOURCE: https://downey.io/notes/dev/ubuntu-sleep-pod-yaml/
#
# $ kubectl exec -it ubuntu -- /bin/bash
# $ apt update && apt install curl -y
#
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    app: ubuntu
spec:
  containers:
  - image: ubuntu
    command:
      - "sleep"
      - "604800"
    imagePullPolicy: IfNotPresent
    name: ubuntu
  restartPolicy: Always
---
# SOURCE: https://cloud.google.com/kubernetes-engine/docs/tutorials/guestbook
#apiVersion: v1
#kind: Service
#metadata:
#  name: dbs-cache-redis-service
##  labels:
##    app: redis
##    role: leader
##    tier: backend
#spec:
#  ports:
#    - protocol: TCP
#      port: 6379
#      targetPort: 6379
#  selector:
#    app: redis
##    role: leader
##    tier: backend
