# SOURCE: https://cloud.google.com/kubernetes-engine/docs/tutorials/guestbook
# Use as cache for each pod with Port 6380.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-cache-redis
  labels:
    app: pod-redis
#    role: leader
#    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-redis
  template:
    metadata:
      labels:
        app: pod-redis
    #        role: leader
    #        tier: backend
    spec:
      containers:
        - name: pod-cache-redis
          image: "docker.io/redis:6.2.6-alpine"
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            # Should to same port in pom.xml and match to targetPort of Service pod
            - containerPort: 6380
---
# SOURCE: https://cloud.google.com/kubernetes-engine/docs/tutorials/guestbook
apiVersion: v1
kind: Service
metadata:
  name: pod-cache-redis-service
#  labels:
#    app: redis
#    role: leader
#    tier: backend
spec:
  #  type: NodePort
  type: ClusterIP
  ports:
    - protocol: TCP
      # The port use in the kubernetes cluster.
      port: 6380
      # Should to same to the port in pom.xml and containerPort.
      targetPort: 6380
  selector:
    app: pod-redis
#    role: leader
#    tier: backend
