apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-db-1-deployment
  labels:
    app: core-db-1
spec:
  selector:
    matchLabels:
      app: core-db-1
  template:
    metadata:
      labels:
        app: core-db-1
    spec:
      containers:
        - name: core-db-1-container
          image: core-db-1:1.0-SNAPSHOT
          ports:
            # Should to same port in pom.xml and match to targetPort of Service pod
            - containerPort: 5050 # 9080
        # Set the environment variables
        # should to create the sys-app-root before apply the 10_kubernetes.yaml
        # $ kubectl create configmap sys-app-root --from-literal cacheHostIP=192.168.49.2 --from-literal cacheHostPort=30000
        # $ kubectl apply -f 10_kubernetes.yaml
        # $ kubectl delete configmap
#          env:
#          - name: CACHE_HOST_IP
#            valueFrom:
#              configMapKeyRef:
#                name: sys-app-root
#                key: cacheHostIP
#                optional: true
#          - name: CACHE_HOST_PORT
#            valueFrom:
#              configMapKeyRef:
#                name: sys-app-root
#                key: cacheHostPort
#                optional: true
---
apiVersion: v1
kind: Service
metadata:
  name: core-db-1-service
spec:
  type: NodePort
  selector:
    app: core-db-1
  ports:
    - protocol: TCP
      # The port use in the kubernetes cluster.
      port: 5050
      # Should to same to the port in pom.xml and containerPort.
      targetPort: 5050
      # Use for external call should be between 30000-32768
      nodePort: 30100
