apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontendui-deployment
  labels:
    app: frontendui
spec:
  selector:
    matchLabels:
      app: frontendui
  template:
    metadata:
      labels:
        app: frontendui
    spec:
      containers:
        - name: frontendui-container
          image: frontendui:1.0-SNAPSHOT
          ports:
            # Should to same port in pom.xml and match to targetPort of Service pod
            - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: frontendui-service
spec:
  type: NodePort
  selector:
    app: frontendui
  ports:
    - protocol: TCP
      # The port use in the kubernetes cluster.
      port: 9090
      # Should to same to the port in pom.xml and containerPort.
      targetPort: 9090
      # Use for external call should be between 30000-32768
      nodePort: 31100
