apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-deployment
  labels:
    app: inventory
spec:
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
        - name: inventory-container
          image: inventory:1.0-SNAPSHOT
          ports:
            # Should to same port in pom.xml and match to targetPort of Service pod
            - containerPort: 9080
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
spec:
  type: NodePort
  selector:
    app: inventory
  ports:
    - protocol: TCP
      # The port use in the kubernetes cluster.
      port: 9080
      # Should to same to the port in pom.xml and containerPort.
      targetPort: 9080
      # Use for external call should be between 30000-32768
      nodePort: 31110
